CREATE TABLE pageviews (
  browser text,
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	inserted_at timestamp WITH time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  ip text,
  os text,
  referrer text,
	user_agent text,
  url text
);

CREATE FUNCTION pageviews_url_count ()
  RETURNS TABLE (
    url text,
    pageviews bigint
  )
  AS $$
  SELECT
    url,
    COUNT(*)
  FROM
    pageviews
  GROUP BY
    1
  ORDER BY
    2 DESC
$$
LANGUAGE sql
STABLE;


CREATE FUNCTION pageviews_browser_count ()
    RETURNS TABLE (
        browser text,
        pageviews bigint
    )
    AS $$
    SELECT
        browser,
        COUNT(*)
    FROM
        pageviews
    GROUP BY
        1
    ORDER BY
        2 DESC
$$
LANGUAGE sql
STABLE;


CREATE FUNCTION pageviews_os_count ()
    RETURNS TABLE (
        os text,
        pageviews bigint
    )
    AS $$
    SELECT
        os,
        COUNT(*)
    FROM
        pageviews
    GROUP BY
        1
    ORDER BY
        2 DESC
$$
LANGUAGE sql
STABLE;